import { Injectable, NotFoundException } from '@nestjs/common';
import { existsSync, mkdirSync } from 'fs';
import { readFile, stat, writeFile as fsWriteFile } from 'fs/promises';
import { dirname, join, resolve } from 'path';

const UPLOAD_ROOT = resolve(__dirname, '..', '..', 'uploads');

/**
 * Dev-only stand-in for the S3-compatible storage the architecture calls
 * for (Phase 1 §3) — no AWS/S3-compatible credentials are available on this
 * machine. Every method here is what a real `S3StorageService` would also
 * need to implement; swapping backends later is a one-file change behind
 * DocumentsService, not a contract change.
 */
@Injectable()
export class LocalStorageService {
  private pathFor(s3Key: string): string {
    // s3Key is generated by this service (see DocumentsService), never taken
    // from client input, so this join is safe from path traversal.
    return join(UPLOAD_ROOT, s3Key);
  }

  async writeFile(s3Key: string, buffer: Buffer): Promise<void> {
    const target = this.pathFor(s3Key);
    mkdirSync(dirname(target), { recursive: true });
    await fsWriteFile(target, buffer);
  }

  async readFile(s3Key: string): Promise<Buffer> {
    const target = this.pathFor(s3Key);
    if (!existsSync(target)) throw new NotFoundException('File not found in storage');
    return readFile(target);
  }

  async fileExists(s3Key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(s3Key));
      return true;
    } catch {
      return false;
    }
  }
}
