import { Injectable, NotFoundException } from '@nestjs/common';
import { existsSync, mkdirSync } from 'fs';
import { readFile, stat, writeFile as fsWriteFile } from 'fs/promises';
import { dirname, join, resolve } from 'path';
import { StorageService } from './storage.service';

const UPLOAD_ROOT = resolve(__dirname, '..', '..', 'uploads');

/**
 * Dev-only stand-in for real object storage — writes to a folder on
 * whatever machine the API happens to be running on. Never use this in
 * production: on Render (and most hosts) the disk is ephemeral, wiped on
 * every deploy and on wake-from-sleep, so anything written here eventually
 * vanishes while the Document DB row silently lives on. See
 * documents.module.ts for the production swap to R2StorageService.
 */
@Injectable()
export class LocalStorageService implements StorageService {
  private pathFor(s3Key: string): string {
    // s3Key is generated by this service (see DocumentsService), never taken
    // from client input, so this join is safe from path traversal.
    return join(UPLOAD_ROOT, s3Key);
  }

  async writeFile(s3Key: string, buffer: Buffer): Promise<void> {
    const target = this.pathFor(s3Key);
    mkdirSync(dirname(target), { recursive: true });
    await fsWriteFile(target, buffer);
  }

  async readFile(s3Key: string): Promise<Buffer> {
    const target = this.pathFor(s3Key);
    if (!existsSync(target)) throw new NotFoundException('File not found in storage');
    return readFile(target);
  }

  async fileExists(s3Key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(s3Key));
      return true;
    } catch {
      return false;
    }
  }
}
